#pragma once

__int8 Setting_Up_Keybinds;

unsigned __int8 User_Commands_Recorder_Record_Bound_To;

unsigned __int8 User_Commands_Recorder_Playback_Bound_To;

unsigned __int32 Original_Window_Procedure_Location;