#pragma once

Copy_User_Command::Dynamic_Allocator_Structure<unsigned __int32, 1> Recorder_User_Comamand_Number_History;

unsigned __int32 Recorder_User_Comamand_Number_History_Number;

unsigned __int32 Recorder_User_Comamand_Number_Greatest_History_Number;

void* Original_Chat_Print_Formatted_Caller_Location;