#pragma once

__int8 Setting_Up_Keybinds;

unsigned __int8 User_Commands_Strafe_Optimizer_Optimize_Bound_To;

unsigned __int8 User_Commands_Recorder_Record_Bound_To;

unsigned __int8 User_Commands_Recorder_Playback_Bound_To;

unsigned __int8 Route_Recorder_Record_Bound_To;

__int8 Visuals_Recorded_Route_Draw;

unsigned __int32 Original_Window_Procedure_Location;