#pragma once

std::vector<unsigned __int32> Recorder_User_Comamand_Number_History;

unsigned __int32 Recorder_User_Comamand_Number_History_Number;

unsigned __int32 Recorder_User_Comamand_Number_Greatest_History_Number;

void* Original_Chat_Print_Formatted_Caller_Location;